export const LANGUAGES = [
  "Arabic",
  "Bengali",
  "Chinese (Mandarin)",
  "Chinese (Cantonese)",
  "Dutch",
  "English",
  "French",
  "German",
  "Greek",
  "Hindi",
  "Italian",
  "Japanese",
  "Korean",
  "Persian",
  "Polish",
  "Portuguese",
  "Russian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tamil",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
] as const;

export const PROFICIENCY_LEVELS = [
  { value: "beginner", label: "Beginner" },
  { value: "intermediate", label: "Intermediate" },
  { value: "advanced", label: "Advanced" },
  { value: "fluent", label: "Fluent" },
  { value: "native", label: "Native" },
] as const;

export const INTEREST_OPTIONS = [
  "Cultural Exchange",
  "Travel",
  "Career Development",
  "Academic Research",
  "Music",
  "Film & TV",
  "Literature",
  "Cooking",
  "Sports",
  "Technology",
  "Art & Design",
  "History",
  "Business",
  "Science",
  "Study Abroad",
] as const;